version: '3.6'
services:
  postgres:
    image: postgres:13.2
    restart: always
    networks:
      - network
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'schedule'
networks:
  network:
    driver: bridge